server:
  port: 2238
spring:
  application:
    name: Employee-jpastreamer
  datasource:
    url: jdbc:mysql://localhost:3306/sharath
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true